services:
  - type: web
    name: backend-service
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r ./backend/requirements.txt
    startCommand: python backend/app.py
